<a href="https://colab.research.google.com/github/mznamira015/Basic-Intro-to-Analytics-and-ML-with-Python/blob/main/lab4DM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# original image matrix
img_matrix = [[3, 4, 2, 8], [7, 3, 1, 3], [2, 5, 6, 7],  [4, 1, 3, 7]]

# desired range for image matrix
new_min = 1
new_max = 20

# calculate the probability and cumulative probability
img_matrix = np.array(img_matrix)
probability = (img_matrix - np.min(img_matrix)) / (np.max(img_matrix) - np.min(img_matrix))
cumulative_probability = probability.cumsum()

# enhance the image matrix
range = (new_max - new_min)+1
enhanced_img_matrix = np.floor( (range* cumulative_probability ))

print(enhanced_img_matrix)


[  5.  14.  17.  37.  54.  59.  59.  65.  68.  79.  94. 111. 119. 119.
 125. 142.]


In [3]:
import numpy as np

# original image matrix
img_matrix = [[3, 4, 2, 8], [7, 3, 1, 3], [2, 5, 6, 7],  [4, 1, 3, 7]]

# desired range for image matrix
new_min = 1
new_max = 20

# calculate the probability and cumulative probability
img_matrix = np.array(img_matrix)
# printing original list
print("The original  image matrix is : " + str(img_matrix))
c = 16

res=dict()
a=[]
for i in img_matrix:
    a.extend(i)
b=set(a)
for i in b:
    res[i]=a.count(i)
    probability = ( res[i] /float(c) )
    print(probability)
for i in b:
    probability = ( res[i] /float(c) )
    cumulative_probability += probability
    print(cumulative_probability)

# enhance the image matrix
range = (new_max - new_min)+1
enhanced_img_matrix = np.floor( (range* cumulative_probability ))

print(enhanced_img_matrix)


The original  image matrix is : [[3 4 2 8]
 [7 3 1 3]
 [2 5 6 7]
 [4 1 3 7]]
0.125
0.125
0.25
0.125
0.0625
0.0625
0.1875
0.0625
[0.125]
[0.25]
[0.5]
[0.625]
[0.6875]
[0.75]
[0.9375]
[1.]
[20.]
